[package]
name = "gssapi-sys"
version = "0.1.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
build = "build.rs"

[features]
gssapi_ext = []

[build-dependencies]
gcc = "^0.3"
pkg-config = "^0.3"
